// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.towl.estoque;

import br.com.towl.estoque.Promocao;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Promocao_Roo_Configurable {
    
    declare @type: Promocao: @Configurable;
    
}
