// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.towl.pessoas;

import br.com.towl.pessoas.Funcionario;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Funcionario_Roo_Configurable {
    
    declare @type: Funcionario: @Configurable;
    
}
