// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.mercadinho.model.pessoas;

import br.com.mercadinho.model.pessoas.Dependente;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Dependente_Roo_Configurable {
    
    declare @type: Dependente: @Configurable;
    
}
