// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.mercadinho.model.pessoas;

import br.com.mercadinho.model.pessoas.Dependente;

privileged aspect Dependente_Roo_JavaBean {
    
    public String Dependente.getNome() {
        return this.nome;
    }
    
    public void Dependente.setNome(String nome) {
        this.nome = nome;
    }
    
}
