// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.mercadinho.model.pessoas;

import br.com.mercadinho.model.pessoas.Registro;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Registro_Roo_Configurable {
    
    declare @type: Registro: @Configurable;
    
}
